import:
  path: /import
  controller: App\Apps\View\Fleet\ImportFleetController
  methods: [ GET ]
  options:
    expose: true

export:
  path: /export
  controller: App\Apps\View\Fleet\ExportFleetController
  methods: [ GET ]
  options:
    expose: true