store:
  path: /store
  controller: App\Apps\Api\Test\StoreTestController
  methods: [POST]
  options:
    expose: true

update:
  path: /update/{id}
  controller: App\Apps\Api\Test\UpdateTestController
  methods:  [POST]
  options:
    expose: true

filter:
  path: /filter
  controller: App\Apps\Api\Test\FilterTestController
  methods: [GET]
  options:
    expose: true