import:
  path: /import
  controller: App\Apps\Api\Vehicle\ImportExcelVehicleController
  methods: [POST]
  options:
    expose: true

export:
  path: /export
  controller: App\Apps\Api\Vehicle\ExportExcelVehicleController
  methods: [POST]
  options:
    expose: true

update:
  path: /update
  controller: App\Apps\Api\Vehicle\VehicleUpdateController
  methods: [POST]
  options:
    expose: true
