apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prj064-dev-importsystem-shared-claim
  namespace: __KubernetesNamespace__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi